
openShift:
  enabled: false

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  

rbac:
  nodeAccess: true

config:
  inputs: |
    [INPUT]
        Name tail
        Tag kube.*
        Path /var/log/containers/*.log
        DB /fluent-bit/tail/kube.db
        DB.Sync Normal
        #  https://raw.githubusercontent.com/fluent/fluent-bit/refs/heads/master/conf/parsers.conf
        multiline.parser cri
        Mem_Buf_Limit 15MB
        Skip_Long_Lines On

  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser Off
        K8S-Logging.Exclude Off
        Labels Off
        Annotations On
        Use_Kubelet On
        Kubelet_Host ${NODE_IP}
        tls.verify Off
        Buffer_Size 0

    [FILTER]
        Name nest
        Match kube.*
        Operation lift
        Nested_under kubernetes
        Add_prefix kubernetes.

    [FILTER]
        name nest
        match kube.*
        operation lift
        nested_under kubernetes.annotations
        add_prefix kubernetes.annotations.

    [FILTER]
        Name nest
        Match kube.*
        Operation nest
        Nest_under dt.metadata
        Wildcard kubernetes.annotations.metadata.dynatrace.com/*

    [FILTER]
        Name nest
        Match kube.*
        Operation lift
        Nested_under dt.metadata
        Remove_prefix kubernetes.annotations.metadata.dynatrace.com/

    [FILTER]
        Name                  multiline
        Match                 kube.*
        multiline.key_content log
        # TODO - Move to Dynatrace openpipeline - go, java & python, multiline-dotnet-logs, multiline-rust-logs
        multiline.parser      go, python, java, multiline-dotnet-logs, multiline-rust-logs

    # [FILTER]
    #     Name                  parser
    #     Match                 kube.*
    #     Key_Name              log
    #     # TODO - Move to Dynatrace openpipeline - multiline-java, multiline-python, multiline-rust
    #     Parser                multiline-dotnet
    #     Parser                multiline-java
    #     Parser                multiline-python
    #     Parser                kafka
    #     Reserve_Data          On
    #     Preserve_Key          On

    [FILTER]
        Name modify
        Match kube.*
        Rename time timestamp
        Rename log content
        Rename level loglevel
        Rename kubernetes.namespace_name k8s.namespace.name
        Rename kubernetes.pod_id k8s.pod.uid
        Rename kubernetes.pod_name k8s.pod.name
        Rename kubernetes.container_name k8s.container.name
        Add k8s.cluster.name ${K8S_CLUSTER_NAME}
        Add k8s.cluster.uid ${K8S_CLUSTER_UID}
        # deprecated, but still in use
        Add dt.kubernetes.cluster.name ${K8S_CLUSTER_NAME}
        Add dt.kubernetes.cluster.id ${K8S_CLUSTER_UID}
        Remove_wildcard kubernetes.

  outputs: |
    # Used for debugging Fluent-bit itself
    # This will echo the record to stdout so you can see it
    # [OUTPUT]
    #     name             stdout
    #     match            *

    [OUTPUT]
        name http
        match *
        header Content-Type application/json; charset=utf-8
        header Authorization Api-Token ${DT_INGEST_TOKEN}
        allow_duplicated_headers false
        host ${DT_INGEST_HOST}
        Port 443
        URI /api/v2/logs/ingest
        Format json
        json_date_format iso8601
        json_date_key timestamp
        tls On
        tls.verify Off

  customParsers: |
    # https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing
    # [PARSER]
    #     Name kafka
    #     Format regex
    #     Time_Key time
    #     Time_Format %Y-%m-%d %H:%M:%S,%L
    #     Regex ^\[(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2},\d{1,3})\] (?<level>ERROR|WARN|INFO) \[?(?<logger>.*)\]? (?<message>.*) \((?<namespace>.*)\)/

    # [PARSER]
    #     Name        multiline-rust
    #     Format      regex
    #     Regex       /^(?<time>\d{1,2}:\d{1,2}:\d{1,2}) \[(?<level>ERROR|WARN|INFO)\] (?<message>.*)/
    #     Time_Key    time
    #     Time_Format %Y-%m-%d %H:%M:%S

    [MULTILINE_PARSER]
        name                      multiline-rust-logs
        type                      regex
        flush_timeout             1000
        rule      "start_state"   "/^(\d{1,2}:\d{1,2}:\d{1,2}) \[(ERROR|WARN|INFO)\].*/"  "cont"
        rule      "cont"          "/^\s+.*/"  "cont"

    # [PARSER]
    #     Name          multiline-dotnet
    #     Format        regex
    #     Regex         ^(?<level>[a-z]+): (?<logger>[^\[]+)\[(?<event_id>[^\]]+)\]\s*(?<message>(?:(?!^[a-z]+:)[\s\S])+)
    #     Time_Key      time
    #     Time_Format   %Y-%m-%d %H:%M:%S

    [MULTILINE_PARSER]
        name          multiline-dotnet-logs
        type          regex
        flush_timeout 1000
        rule      "start_state"   "/^(warn|info|fail|dbug): .*/"        "cont"
        rule      "cont"          "/^\s+.*/"                       "cont"
    
    # TODO - Move to Dynatrace openpipeline
    # [PARSER]
    #     Name        multiline-python
    #     Format      regex
    #     Regex       /^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2},\d{1,3}) (?<level>ERROR|WARN|INFO) \[(?<logger>[^\[]+)\] \[(?<location>[^\[]+)\] (?<message>.*)/
    #     Time_Key    time
    #     Time_Format %Y-%m-%d %H:%M:%S

    # [MULTILINE_PARSER]
    #     name                      multiline-python-logs
    #     type                      regex
    #     flush_timeout             1000
    #     rule      "start_state"   "/^(\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2},\d{1,3}) (ERROR|WARN|INFO).*/"  "cont"
    #     rule      "cont"          "/^\s+.*/"  "cont"

    # [PARSER]
    #     Name        multiline-java
    #     Format      regex
    #     Regex       /(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}) - (?<level>FATAL|ERROR|WARN|INFO|DEBUG|TRACE|ALL)  (?<logger>[^\s]+) (?<message>.*)/
    #     Time_Key    time
    #     Time_Format %Y-%m-%d %H:%M:%S

    # [MULTILINE_PARSER]
    #     name                      multiline-java-logs
    #     type                      regex
    #     flush_timeout             1000
    #     rule      "start_state"   "/^(\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}) - (FATAL|ERROR|WARN|INFO|DEBUG|TRACE|ALL).*/"  "cont"
    #     rule      "cont"          "/^\s+.*/"  "cont"

daemonSetVolumes:
  - hostPath:
      path: /var/lib/fluent-bit/
    name: positions
  - hostPath:
      path: /var/log/containers
    name: containers
  - hostPath:
      path: /var/log/pods
    name: pods

daemonSetVolumeMounts:
  - mountPath: /fluent-bit/tail
    name: positions
  - mountPath: /var/log/containers
    name: containers
    readOnly: true
  - mountPath: /var/log/pods
    name: pods
    readOnly: true

podAnnotations:
  dynatrace.com/inject: "false"
  #metrics.dynatrace.com/path: "/api/v1/metrics/prometheus"
  #metrics.dynatrace.com/port: "2020"
  #metrics.dynatrace.com/scrape: "true"

envWithTpl:
  - name: K8S_CLUSTER_UID
    value: '{{ (lookup "v1" "Namespace" "" "kube-system").metadata.uid }}'

env:
  - name: K8S_CLUSTER_NAME
    value: <K8S_CLUSTER_NAME>
  - name: DT_INGEST_TOKEN
    value: <DT_INGEST_TOKEN>
  - name: DT_INGEST_HOST
    value: <DT_INGEST_HOST>
  - name: NODE_IP
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: status.hostIP