configs:
  - id: service-naming-astroshop
    config:
      name: Astroshop service naming
      template: service-naming-astroshop.json
      skip: true
    type:
      api: conditional-naming-service
    environmentOverrides:
      - environment: staging
        override:
          skip: false
