spec:
  template:
    metadata:
      annotations:
        oneagent.dynatrace.com/inject: "false"   
        metadata.dynatrace.com/process.technology: "python"       
    spec:
      containers:
        - name: loadgenerator
          image:shinojosa/astroshop:1.11.1-loadgenerator
          imagePullPolicy: Always
          env:
            - name: LOCUST_HOST
              value: http://astroshop-stg.k8s-demo.dynatracelabs.com
            - name: OTEL_COLLECTOR_NAME
              value: 'dynatrace-otel-gateway-collector'
          resources:
            limits:
              memory: 2Gi