apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-catalog-storage
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azureblob-nfs-premium
  resources:
    requests:
      storage: 5Gi